x-logging:
  &default-logging
  options:
    max-size: '12m'
    max-file: '5'
  driver: json-file

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - admin_ui_build:/usr/share/nginx/html/admin:ro
      - nginx_logs:/var/log/nginx
    networks:
      - internal_net
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "8079" # nginx status
    depends_on:
      - api
      - links
      
  api:
    image: bneibaruch/mdb:${API_VERSION}
    container_name: api
    restart: unless-stopped
    volumes:
      - ./api/config.toml:/app/config.toml
    networks:
      - internal_net
    expose:
      - "8080"
    logging: *default-logging
    environment:
      MDB_URL: postgres://${MDB_USER}:${MDB_PASSWORD}@${MDB_HOST}:${MDB_PORT}/${MDB_DATABASE}?sslmode=disable
      SERVER_ROLLBAR_TOKEN: ${ROLLBAR_TOKEN}
    
  links:
    image: bneibaruch/mdb_links:${LINKS_VERSION}
    container_name: links
    restart: unless-stopped
    networks:
      - internal_net
    expose:
      - "8081"
    logging: *default-logging
    environment:
      GIN_MODE: release
      BASE_URL: http://app.mdb.bbdomain.org/links/
      MDB_URL: postgres://${MDB_USER}:${MDB_PASSWORD}@{MDB_HOST}:${MDB_PORT}/${MDB_DATABASE}?sslmode=disable
      FILER_URLS: "http://files.bbdomain.org/api/v1/get"
      ROLLBAR_TOKEN: ${ROLLBAR_TOKEN}
      ROLLBAR_ENVIRONMENT: internal
      MDB_MAX_OPEN_CONNS: 10
  
  admin_ui:
    image: bneibaruch/mdb_admin:${ADMIN_UI_VERSION}
    container_name: admin_ui
    volumes:
      - admin_ui_build:/build_copy

  archive_content_pusher:
    image: bneibaruch/archive_content_pusher:${ARCHIVE_CONTENT_PUSHER_VERSION}
    container_name: 'acp'
    environment:
      - LAITMAN_RU_URL=${LAITMAN_RU_URL}
      - LAITMAN_RU_USERNAME=${LAITMAN_RU_USERNAME}
      - LAITMAN_RU_PASSWORD=${LAITMAN_RU_PASSWORD}

  nats:
    image: nats:2.11
    container_name: nats
    restart: unless-stopped
    volumes:
      - nats_data:/storage
    ports:
      - "4222:4222"    # client connections
    expose:
      - "8222" # monitoring
    networks:
      - internal_net
    command: ["--jetstream", "--store_dir", "/storage", "--user", "${NATS_USER}", "--pass", "${NATS_PASSWORD}", "--http_port", "8222"]

  grafana_alloy:
    image: grafana/alloy:latest
    container_name: grafana_alloy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./monitoring/alloy.config.hcl:/etc/alloy/config.alloy.hcl:ro
      - nginx_logs:/nginx_logs:ro
    command:
      - run
      - /etc/alloy/config.alloy.hcl
    networks:
      - internal_net

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx_exporter
    restart: unless-stopped
    command:
      - -nginx.scrape-uri=http://nginx:8079/nginx_status
    networks:
      - internal_net
    ports:
      - "9113:9113"

  nats-exporter:
    image: natsio/prometheus-nats-exporter:latest
    container_name: nats_exporter
    command:
      - "-accstatz"
      - "-connz_detailed"
      - "-healthz_js_enabled_only"
      - "-varz"
      - "-subz"
      - "-jsz=all"
      - "http://nats:8222"
    ports:
      - "9116:7777"
    networks:
      - internal_net

networks:
  internal_net:
    driver: bridge

volumes:
  admin_ui_build:
  nginx_logs:
  nats_data:

