[server]
bind-address=":8080"
mode="release"
rollbar-token=""
rollbar-environment="internal"
log="./logs/mdb.log"
docs="./docs.html"

[mdb]
url=""

[storage]
api-url="http://files.bbdomain.org/api/v1/"
index-directory="/sites/mdb/storage/.index/"

[nats]
url="nats://nats:4222"
pub-ack-wait="5s"
client-id="mdb-api"
cluster-id="test-cluster"
subject="mdb2"

[events]
handlers=["logger", "nats"]
emitter-size=1024

[authentication]
enable=true
issuers=[
	"https://accounts.kab.info/auth/realms/main"
]

[permissions]
enable=true
log=false

[twitter]
access-token=""
access-token-secret=""
consumer-key=""
consumer-secret=""

[wordpress.laitman-ru]
url="https://www.laitman.ru/"
username=""
password=""

[wordpress.laitman-co-il]
url="https://laitman.co.il/"
username=""
password=""

[wordpress.laitman-com]
url="https://laitman.com/"
username=""
password=""

[wordpress.laitman-es]
url="https://laitman.es/"
username=""
password=""